import React from 'react';
import './textures.css';
import * as texture from './texture.jsx';
export default props => {
    var handleUpdate = props.update;
    console.log("handleUpdate");
    return (<div className="dropdown-list-container">
        <svg className="texture-item svg-texture-none" onClick={() => handleUpdate(texture.none)}></svg>
        <svg className="texture-item svg-texture-graph-paper" onClick={() => handleUpdate(texture.graphPaper)}></svg>
        <svg className="texture-item svg-texture-texture" onClick={() => handleUpdate(texture.texture)}></svg>
        <svg className="texture-item svg-texture-formal-invitation" onClick={() => handleUpdate(texture.formalInvitation)}></svg>
        <svg className="texture-item svg-texture-topography" onClick={() => handleUpdate(texture.topography)}></svg>
        <svg className="texture-item svg-texture-hexagons" onClick={() => handleUpdate(texture.hexagons)}></svg>
        <svg className="texture-item svg-texture-hideout" onClick={() => handleUpdate(texture.hideout)}></svg>
        <svg className="texture-item svg-texture-brick-wall" onClick={() => handleUpdate(texture.brickWall)}></svg>
        <svg className="texture-item svg-texture-squares" onClick={() => handleUpdate(texture.squares)}></svg>
        <svg className="texture-item svg-texture-falling-triangles" onClick={() => handleUpdate(texture.fallingTriangles)}></svg>
        <svg className="texture-item svg-texture-pie-factory" onClick={() => handleUpdate(texture.pieFactory)}></svg>
        <svg className="texture-item svg-texture-stripes" onClick={() => handleUpdate(texture.stripes)}></svg>
        <svg className="texture-item svg-texture-charlie-brown" onClick={() => handleUpdate(texture.charlieBrown)}></svg>
        <svg className="texture-item svg-texture-autumn" onClick={() => handleUpdate(texture.autumn)}></svg>
        <svg className="texture-item svg-texture-temple" onClick={() => handleUpdate(texture.temple)}></svg>
        <svg className="texture-item svg-texture-stamp-collection" onClick={() => handleUpdate(texture.stampCollection)}></svg>
        <svg className="texture-item svg-texture-death-star" onClick={() => handleUpdate(texture.deathStar)}></svg>
        <svg className="texture-item svg-texture-church-on-sunday" onClick={() => handleUpdate(texture.churchOnSunday)}></svg>
        <svg className="texture-item svg-texture-overlapping-hexagons" onClick={() => handleUpdate(texture.overlappingCircles)}></svg>
        <svg className="texture-item svg-texture-4-point-stars" onClick={() => handleUpdate(texture.fourPointStars)}></svg>
        <svg className="texture-item svg-texture-bamboo" onClick={() => handleUpdate(texture.bamboo)}></svg>
        <svg className="texture-item svg-texture-bathroom-floor" onClick={() => handleUpdate(texture.bathroomFloor)}></svg>
        <svg className="texture-item svg-texture-cork-screw" onClick={() => handleUpdate(texture.corkScrew)}></svg>
        <svg className="texture-item svg-texture-happy-intersection" onClick={() => handleUpdate(texture.happyIntersection)}></svg>
        <svg className="texture-item svg-texture-libson" onClick={() => handleUpdate(texture.libson)}></svg>
        <svg className="texture-item svg-texture-steel-beams" onClick={() => handleUpdate(texture.steelBeams)}></svg>
        <svg className="texture-item svg-texture-tiny-checkers" onClick={() => handleUpdate(texture.tinyCheckers)}></svg>
        <svg className="texture-item svg-texture-x-equals" onClick={() => handleUpdate(texture.xEquals)}></svg>
        <svg className="texture-item svg-texture-anchors-away" onClick={() => handleUpdate(texture.anchorsAway)}></svg>
        <svg className="texture-item svg-texture-bevel-circle" onClick={() => handleUpdate(texture.bevelCircle)}></svg>
        <svg className="texture-item svg-texture-fancy-rectangles" onClick={() => handleUpdate(texture.fancyRectangles)}></svg>
        <svg className="texture-item svg-texture-heavy-rain" onClick={() => handleUpdate(texture.heavyRain)}></svg>
        <svg className="texture-item svg-texture-overlapping-circles" onClick={() => handleUpdate(texture.overlappingCircles)}></svg>
        <svg className="texture-item svg-texture-plus" onClick={() => handleUpdate(texture.plus)}></svg>
        <svg className="texture-item svg-texture-rounded-plus-connected" onClick={() => handleUpdate(texture.roundedPlusConnected)}></svg>
        <svg className="texture-item svg-texture-volcano-lamp" onClick={() => handleUpdate(texture.volcanoLamp)}></svg>
        <svg className="texture-item svg-texture-wiggle" onClick={() => handleUpdate(texture.wiggle)}></svg>
        <svg className="texture-item svg-texture-bubbles" onClick={() => handleUpdate(texture.bubbles)}></svg>
        <svg className="texture-item svg-texture-cage" onClick={() => handleUpdate(texture.cage)}></svg>
        <svg className="texture-item svg-texture-connections" onClick={() => handleUpdate(texture.connections)}></svg>
        <svg className="texture-item svg-texture-current" onClick={() => handleUpdate(texture.current)}></svg>
        <svg className="texture-item svg-texture-diagonal-stripes" onClick={() => handleUpdate(texture.diagonalStripes)}></svg>
        <svg className="texture-item svg-texture-flipped-diamonds" onClick={() => handleUpdate(texture.flippedDiamonds)}></svg>
        <svg className="texture-item svg-texture-floating-cogs" onClick={() => handleUpdate(texture.floatingCogs)}></svg>
        <svg className="texture-item svg-texture-glamorous" onClick={() => handleUpdate(texture.glamorous)}></svg>
        <svg className="texture-item svg-texture-houndstooth" onClick={() => handleUpdate(texture.houndstooth)}></svg>
        <svg className="texture-item svg-texture-leaf" onClick={() => handleUpdate(texture.leaf)}></svg>
        <svg className="texture-item svg-texture-moroccan" onClick={() => handleUpdate(texture.moroccan)}></svg>
        <svg className="texture-item svg-texture-morphing-diamonds" onClick={() => handleUpdate(texture.morphingDiamonds)}></svg>
        <svg className="texture-item svg-texture-rails" onClick={() => handleUpdate(texture.rails)}></svg>
        <svg className="texture-item svg-texture-rain" onClick={() => handleUpdate(texture.rain)}></svg>
        <svg className="texture-item svg-texture-skulls" onClick={() => handleUpdate(texture.skulls)}></svg>
        <svg className="texture-item svg-texture-squares-in-squares" onClick={() => handleUpdate(texture.squaresInSquares)}></svg>
        <svg className="texture-item svg-texture-tic-tac-toe" onClick={() => handleUpdate(texture.ticTacToe)}></svg>
        <svg className="texture-item svg-texture-zig-zag" onClick={() => handleUpdate(texture.zigZag)}></svg>
        <svg className="texture-item svg-texture-aztec" onClick={() => handleUpdate(texture.aztec)}></svg>
        <svg className="texture-item svg-texture-bank-note" onClick={() => handleUpdate(texture.bankNote)}></svg>
        <svg className="texture-item svg-texture-boxes" onClick={() => handleUpdate(texture.boxes)}></svg>
        <svg className="texture-item svg-texture-circles-and-squares" onClick={() => handleUpdate(texture.circlesAndSquares)}></svg>
        <svg className="texture-item svg-texture-circuit-board" onClick={() => handleUpdate(texture.circuitBoard)}></svg>
        <svg className="texture-item svg-texture-curtain" onClick={() => handleUpdate(texture.curtain)}></svg>
        <svg className="texture-item svg-texture-diagonal-lines" onClick={() => handleUpdate(texture.diagonalLines)}></svg>
        <svg className="texture-item svg-texture-endless-clouds" onClick={() => handleUpdate(texture.endlessClouds)}></svg>
        <svg className="texture-item svg-texture-eyes" onClick={() => handleUpdate(texture.eyes)}></svg>
        <svg className="texture-item svg-texture-floor-tile" onClick={() => handleUpdate(texture.floorTile)}></svg>
        <svg className="texture-item svg-texture-groovy" onClick={() => handleUpdate(texture.groovy)}></svg>
        <svg className="texture-item svg-texture-intersecting-cirles" onClick={() => handleUpdate(texture.intersectingCirles)}></svg>
        <svg className="texture-item svg-texture-melt" onClick={() => handleUpdate(texture.melt)}></svg>
        <svg className="texture-item svg-texture-overlapping-diamonds" onClick={() => handleUpdate(texture.overlappingDiamonds)}></svg>
        <svg className="texture-item svg-texture-parkay-floor" onClick={() => handleUpdate(texture.parkayFloor)}></svg>
        <svg className="texture-item svg-texture-pixel-dots" onClick={() => handleUpdate(texture.pixelDots)}></svg>
        <svg className="texture-item svg-texture-polka-dots" onClick={() => handleUpdate(texture.polkaDots)}></svg>
        <svg className="texture-item svg-texture-signal" onClick={() => handleUpdate(texture.signal)}></svg>
        <svg className="texture-item svg-texture-slanted-stars" onClick={() => handleUpdate(texture.slantedStars)}></svg>
        <svg className="texture-item svg-texture-wallpaper" onClick={() => handleUpdate(texture.wallpaper)}></svg>
        <svg className="texture-item svg-texture-dominos" onClick={() => handleUpdate(texture.dominos)}></svg>
        <svg className="texture-item svg-texture-architect" onClick={() => handleUpdate(texture.architect)}></svg>
        <svg className="texture-item svg-texture-cutout" onClick={() => handleUpdate(texture.cutout)}></svg>
        <svg className="texture-item svg-texture-overcast" onClick={() => handleUpdate(texture.overcast)}></svg>
        <svg className="texture-item svg-texture-jigsaw" onClick={() => handleUpdate(texture.jigsaw)}></svg>
    </div>);
}